[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
solc_version = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
bytecode_hash = "none"
auto_detect_remappings = false
fs_permissions = [{ access = "write", path = "./e2e/local.json" }] # script/LocalSetup.s.sol (local e2e only)

[profile.default.fuzz]
runs = 256

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
